---
variables:
  DOCKER_REGISTRY: buildd.escaux.com
  DOCKER_IMAGE_NAME: synapse

apply-patches:
  stage: .pre
  tags:
    - buildd3
    - shell
  script:
    - export QUILT_PATCHES=patches
    - quilt push -a

compute-image-tag:
  stage: .pre
  tags:
    - buildd3
    - shell
  script:
    - test -n "${CI_COMMIT_REF_NAME}" && export DOCKER_IMAGE_TAG=${CI_COMMIT_REF_NAME}
    - test -n "${CI_COMMIT_TAG}" && export DOCKER_IMAGE_TAG=${CI_COMMIT_TAG} || true
    - echo "DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG}" >> build.env
  artifacts:
    reports:
      dotenv: build.env

setup-buildx:
  stage: .pre
  tags:
    - buildd3
    - shell
  script:
    - DOCKER_BUILDX_BUILDER=builder-$(cat /proc/sys/kernel/random/uuid)
    - echo "DOCKER_BUILDX_BUILDER=${DOCKER_BUILDX_BUILDER}" >> build.env
    - docker info
    - docker buildx version
    - docker buildx create --name ${DOCKER_BUILDX_BUILDER} --driver docker-container --buildkitd-flags '--allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host' --use
    - docker buildx inspect --bootstrap --builder ${DOCKER_BUILDX_BUILDER}
  artifacts:
    reports:
      dotenv: build.env

build-container:
  stage: build
  tags:
    - buildd3
    - shell
  script:
    - echo "Will tag build as ${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
    - docker buildx build --file docker/Dockerfile --platform linux/amd64 --tag ${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} --push .

cleanup:
  stage: .post
  tags:
    - buildd3
    - shell
  script:
    - docker buildx rm $DOCKER_BUILDX_BUILDER
